spring:
  application:
    name: clusteringservice
  kafka:
    max:
      message:
        bytes: 7000000

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  servlet:
    session:
      cookie:
        http-only: true


kafka:
  topic: fileadded
  bootstrapAddress: 192.168.0.26:9092,192.168.0.26:9093,192.168.0.26:9094

elasticsearch:
  clustername: docker-cluster
  host: 172.20.0.1
  port: 9300


datamock:
    count:
        user: 10000
        flat: 100


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka
  instance:
    preferIpAddress: true
