spring:
  application:
    name: clusteringservice
  kafka:
    max:
      message:
        bytes: 7000000

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  servlet:
    session:
      cookie:
        http-only: true
  port: 8081


kafka:
  topic: fileadded
  bootstrapAddress: 192.168.0.26:9092,192.168.0.26:9093,192.168.0.26:9094

elasticsearch:
  clustername: docker-cluster
  host: 192.168.0.26
  port: 9300


datamock:
    count:
        user: 10000
        flat: 100


eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    preferIpAddress: true


