logging:
  level:
    ROOT: DEBUG
    com.antiplagiarism.fileuploadservice: DEBUG

spring:
  profiles:
    active: dev

  devtools:
    restart:
      enabled: true

  jackson:
    serialization:
      indent-output: true

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    preferIpAddress: true



elasticsearch:
  clustername: docker-cluster
  host: 192.168.0.26
  port: 9300

datamock:
  count:
    user: 1000
    flat: 100
